apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: myfamily-net-in-tls
spec:
  secretName: myfamily-net-in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: myfamily.net.in
  dnsNames:
    - myfamily.net.in
    - www.myfamily.net.in
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - myfamily.net.in
          - www.myfamily.net.in

          